name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t k3s-demo-api:test ./app

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: k3s-demo-api:test
          format: table
          exit-code: "1"
          severity: CRITICAL
          ignore-unfixed: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag k3s-demo-api:test ghcr.io/mattraw57/k3s-demo-api:${{ github.sha }}
          docker tag k3s-demo-api:test ghcr.io/mattraw57/k3s-demo-api:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/mattraw57/k3s-demo-api:${{ github.sha }}
          docker push ghcr.io/mattraw57/k3s-demo-api:latest
